# Data Cleaning

## Data Loading

In [1]:
# library imports
import pandas as pd

In [2]:
# invoices
invoices = pd.read_csv('../Data/Original/invoices.csv')
invoices.head()

,invoice_id,vendor_id,invoice_number,invoice_date,due_date,invoice_amount,approval_status,received_date,approved_date
0,INV000001,V0089,50188-430,12/29/25,2/12/26,58912.34,Approved,12/30/25,1/7/26
1,INV000002,V0081,30728-872,1/25/25,3/11/25,62327.30,Approved,1/26/25,2/10/25
2,INV000003,V0072,94834-463,11/14/23,1/13/24,56412.67,Approved,11/15/23,11/23/23
3,INV000004,V0032,62470-544,6/6/24,8/5/24,2152.84,Approved,6/7/24,6/10/24
4,INV000005,V0019,83954-320,3/23/24,4/22/24,33368.21,Submitted,3/23/24,NaN

In [3]:
# invoice charges
invoice_charges = pd.read_csv('../Data/Original/invoice_charges.csv')
invoice_charges.head()

   charge_id invoice_id project_id  charge_amount charge_type
0  CHG000001  INV000001   PRJ-0026       22343.36     Expense
1  CHG000002  INV000001   PRJ-0038       36568.98   Materials
2  CHG000003  INV000002   PRJ-0018       62327.30   Materials
3  CHG000004  INV000003    OH-0006       19924.15     Expense
4  CHG000005  INV000003   PRJ-0025       14996.56     Expense

In [4]:
# payments
payments = pd.read_csv('../Data/Original/payments.csv')
payments.head()

,payment_id,invoice_id,payment_date,payment_amount,payment_method,payment_status
0,PAY000001,INV000001,03/04/26,33792.23,ACH,Cleared
1,PAY000002,INV000002,03/04/25,20418.42,ACH,Cleared
2,PAY000003,INV000002,04/09/25,41908.88,Wire,Cleared
3,PAY000004,INV000003,01/26/24,56412.67,Wire,Cleared
4,PAY000005,INV000004,08/04/24,1158.74,ACH,Cleared

In [5]:
# projects
projects = pd.read_csv('../Data/Original/projects.csv')
projects.head()

,project_id,project_name,client_name,project_type,project_status,project_manager,budget_amount,start_date,end_date
0,OH-0001,Corporate Overhead - General Administration,Internal,overhead,Active,Finance Department,1200000,1/1/24,NaN
1,OH-0002,Corporate IT Systems And Infrastructure,Internal,overhead,Active,IT Department,950000,1/1/24,NaN
2,OH-0003,Human Resources And Recruiting,Internal,overhead,Active,HR Department,420000,1/1/24,NaN
3,OH-0004,Marketing And Business Development,Internal,overhead,Active,Marketing Department,650000,1/1/24,NaN
4,OH-0005,Office Operations And Facilities,Internal,overhead,Active,Operations Department,580000,1/1/24,NaN

In [6]:
# vendors
vendors = pd.read_csv('../Data/Original/vendors.csv')
vendors.head()

,vendor_id,vendor_name,vendor_type,payment_terms,active_flag
0,V0001,1220 Exhibits Inc,Vendor,Net 30,1
1,V0002,192 Branch Interior Services Inc,Vendor,Net 45,1
2,V0003,514 Potter Ave Corp,Vendor,Net 60,1
3,V0004,A A D Construction Corp,Vendor,Net 30,1
4,V0005,A Colarusso & Son Inc,Vendor,Net 45,1

## Data Cleaning

### Invoices

In [7]:
# total invoices count
print('INVOICES:')
print('Total count:')
print(invoices.count(), '\n')

# check datatypes
print('Data type:')
print(invoices.dtypes, '\n')

# Check total missing values per column
print('Missing values:')
print(invoices.isna().sum(), '\n')

# Check for duplicates
print('Duplicate values:')
print(invoices.duplicated().sum(), '\n')

# missing values in approved_date are expected

INVOICES:
Total count:
invoice_id         1000
vendor_id          1000
invoice_number     1000
invoice_date       1000
due_date           1000
invoice_amount     1000
approval_status    1000
received_date      1000
approved_date       750
dtype: int64

Data type:
invoice_id          object
vendor_id           object
invoice_number      object
invoice_date        object
due_date            object
invoice_amount     float64
approval_status     object
received_date       object
approved_date       object
dtype: object

Missing values:
invoice_id           0
vendor_id            0
invoice_number       0
invoice_date         0
due_date             0
invoice_amount       0
approval_status      0
received_date        0
approved_date      250
dtype: int64

Duplicate values:
0

In [8]:
# convert dates to datetime
date_cols = ['invoice_date', 'received_date', 'due_date', 'approved_date']
invoices[date_cols] = invoices[date_cols].apply(pd.to_datetime, format='mixed' , errors='coerce')

# Apply appropriate datatypes
invoices = invoices.astype({
    'invoice_id': 'string',
    'vendor_id': 'string',
    'invoice_number': 'string',
    'approval_status': 'category'
})

invoices.dtypes

invoice_id         string[python]
vendor_id          string[python]
invoice_number     string[python]
invoice_date       datetime64[ns]
due_date           datetime64[ns]
invoice_amount            float64
approval_status          category
received_date      datetime64[ns]
approved_date      datetime64[ns]
dtype: object

### Invoice Charges

In [9]:
# invoice_charges count
print('INVOICE_CHARGES:')
print('Total count:')
print(invoice_charges.count(), '\n')

# check datatypes
print('Data type:')
print(invoice_charges.dtypes, '\n')

# Check total missing values per column
print('Missing values:')
print(invoice_charges.isna().sum(), '\n')

# Check for duplicates
print('Duplicate values:')
print(invoice_charges.duplicated().sum(), '\n')

INVOICE_CHARGES:
Total count:
charge_id        2510
invoice_id       2510
project_id       2510
charge_amount    2510
charge_type      2510
dtype: int64

Data type:
charge_id         object
invoice_id        object
project_id        object
charge_amount    float64
charge_type       object
dtype: object

Missing values:
charge_id        0
invoice_id       0
project_id       0
charge_amount    0
charge_type      0
dtype: int64

Duplicate values:
0

In [10]:
# Apply appropriate datatypes
string_cols = ['charge_id', 'invoice_id', 'project_id']
invoice_charges[string_cols] = invoice_charges[string_cols].astype('string')

invoice_charges['charge_type'] = invoice_charges['charge_type'].astype('category')

invoice_charges.dtypes

charge_id        string[python]
invoice_id       string[python]
project_id       string[python]
charge_amount           float64
charge_type            category
dtype: object

### Payments

In [11]:
# payments count
print('PAYMENTS:')
print('Total count:')
print(payments.count(), '\n')

# check datatypes
print('Data type:')
print(payments.dtypes, '\n')

# Check total missing values per column
print('Missing values:')
print(payments.isna().sum(), '\n')

# Check for duplicates
print('Duplicate values:')
print(payments.duplicated().sum(), '\n')

PAYMENTS:
Total count:
payment_id        1126
invoice_id        1126
payment_date      1126
payment_amount    1126
payment_method    1126
payment_status    1126
dtype: int64

Data type:
payment_id         object
invoice_id         object
payment_date       object
payment_amount    float64
payment_method     object
payment_status     object
dtype: object

Missing values:
payment_id        0
invoice_id        0
payment_date      0
payment_amount    0
payment_method    0
payment_status    0
dtype: int64

Duplicate values:
0

In [12]:
# Apply appropriate datatypes
payments['payment_date'] = payments['payment_date'].apply(pd.to_datetime, format='mixed' , errors='coerce')

payments = payments.astype({
    'payment_id': 'string',
    'invoice_id': 'string',
    'payment_method': 'category',
    'payment_status': 'category'
})

payments.dtypes

payment_id        string[python]
invoice_id        string[python]
payment_date      datetime64[ns]
payment_amount           float64
payment_method          category
payment_status          category
dtype: object

### Projects

In [13]:
# projects count
print('PROJECTS:')
print('Total count:')
print(projects.count(), '\n')

# check datatypes
print('Data type:')
print(projects.dtypes, '\n')

# Check total missing values per column
print('Missing values:')
print(projects.isna().sum(), '\n')

# Check for duplicates
print('Duplicate values:')
print(projects.duplicated().sum(), '\n')

# missing end date values are expected

PROJECTS:
Total count:
project_id         50
project_name       50
client_name        50
project_type       50
project_status     50
project_manager    50
budget_amount      50
start_date         50
end_date           40
dtype: int64

Data type:
project_id         object
project_name       object
client_name        object
project_type       object
project_status     object
project_manager    object
budget_amount       int64
start_date         object
end_date           object
dtype: object

Missing values:
project_id          0
project_name        0
client_name         0
project_type        0
project_status      0
project_manager     0
budget_amount       0
start_date          0
end_date           10
dtype: int64

Duplicate values:
0

In [14]:
# Apply appropriate datatypes
projects['start_date'] = projects['start_date'].apply(pd.to_datetime, format='mixed' , errors='coerce')
projects['end_date'] = projects['end_date'].apply(pd.to_datetime, format='mixed' , errors='coerce')

projects = projects.astype({
    'project_id': 'string',
    'project_name': 'string',
    'client_name': 'string',
    'project_type': 'category',
    'project_status': 'category',
    'project_manager': 'string',
    'budget_amount': 'float64'
    
})

projects.dtypes

project_id         string[python]
project_name       string[python]
client_name        string[python]
project_type             category
project_status           category
project_manager    string[python]
budget_amount             float64
start_date         datetime64[ns]
end_date           datetime64[ns]
dtype: object

### Vendors

In [15]:
# vendors count
print('VENDORS:')
print('Total count:')
print(vendors.count(), '\n')

# check datatypes
print('Data type:')
print(vendors.dtypes, '\n')

# Check total missing values per column
print('Missing values:')
print(vendors.isna().sum(), '\n')

# Check for duplicates
print('Duplicate values:')
print(vendors.duplicated().sum(), '\n')

VENDORS:
Total count:
vendor_id        100
vendor_name      100
vendor_type      100
payment_terms    100
active_flag      100
dtype: int64

Data type:
vendor_id        object
vendor_name      object
vendor_type      object
payment_terms    object
active_flag       int64
dtype: object

Missing values:
vendor_id        0
vendor_name      0
vendor_type      0
payment_terms    0
active_flag      0
dtype: int64

Duplicate values:
0

In [16]:
# Apply appropriate datatypes
vendors = vendors.astype({
    'vendor_id': 'string',
    'vendor_name': 'string',
    'vendor_type': 'category',
    'payment_terms': 'category',
    'active_flag': 'category'
    
})

vendors.dtypes

vendor_id        string[python]
vendor_name      string[python]
vendor_type            category
payment_terms          category
active_flag            category
dtype: object

## Data Exports

In [17]:
# Cleaned datasets were saved as pickle files locally to preserve pandas data types between notebooks. 
# CSV versions are included in the repository for transparency.

# export cleaned data to pickle to preserve data types
invoices.to_pickle('../Data/Cleaned/invoices_cleaned.pkl')
invoice_charges.to_pickle('../Data/Cleaned/invoice_charges_cleaned.pkl')
payments.to_pickle('../Data/Cleaned/payments_cleaned.pkl')
projects.to_pickle('../Data/Cleaned/projects_cleaned.pkl')
vendors.to_pickle('../Data/Cleaned/vendors_cleaned.pkl')

# export cleaned data to csv
invoices.to_csv('../Data/Cleaned/invoices_cleaned.csv')
invoice_charges.to_csv('../Data/Cleaned/invoice_charges_cleaned.csv')
payments.to_csv('../Data/Cleaned/payments_cleaned.csv')
projects.to_csv('../Data/Cleaned/projects_cleaned.csv')
vendors.to_csv('../Data/Cleaned/vendors_cleaned.csv')